"""initial schema

Revision ID: d22bbd14c60e
Revises: 
Create Date: 2026-04-08 13:05:01.816055
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd22bbd14c60e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisory_tips',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('title_kn', sa.String(length=300), nullable=True),
    sa.Column('body_en', sa.Text(), nullable=True),
    sa.Column('body_kn', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('health', 'feeding', 'breeding', 'government', name='advisory_category'), nullable=False),
    sa.Column('species_applicable', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Enum('ICAR', 'KMF', 'NABARD', 'Community', name='advisory_source'), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_ingredients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_kn', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('roughage', 'concentrate', 'supplement', 'mineral', name='feed_category'), nullable=False),
    sa.Column('protein_pct', sa.Float(), nullable=False),
    sa.Column('energy_kcal', sa.Float(), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('availability_season', sa.String(length=100), nullable=True),
    sa.Column('locally_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('govt_schemes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scheme_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('ministry', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_subsidy_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('subsidy_percentage', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_code')
    )
    op.create_table('medicines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_kn', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('withdrawal_milk_days', sa.Integer(), nullable=False),
    sa.Column('withdrawal_meat_days', sa.Integer(), nullable=False),
    sa.Column('species_applicable', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traditional_remedies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_kn', sa.String(length=200), nullable=True),
    sa.Column('plant_ingredient', sa.String(length=200), nullable=False),
    sa.Column('preparation_method', sa.Text(), nullable=True),
    sa.Column('dosage_by_species', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conditions_treated', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_rating', sa.Enum('traditional', 'studied', 'icar_validated', name='evidence_rating'), nullable=False),
    sa.Column('safety_warnings', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'admin', 'vet', 'milk_center', name='user_role'), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lang_pref', sa.String(length=5), server_default='kn', nullable=False),
    sa.Column('location_district', sa.String(length=100), nullable=True),
    sa.Column('location_state', sa.String(length=50), server_default='Karnataka', nullable=False),
    sa.Column('village_code', sa.String(length=20), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('weather_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('low', 'moderate', 'severe', 'extreme', name='alert_severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=100), server_default='IMD', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pashu_aadhaar_id', sa.String(length=12), nullable=False),
    sa.Column('species', sa.Enum('cattle', 'goat', 'sheep', 'poultry', name='species'), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('breed_type', sa.Enum('indigenous', 'crossbreed', 'exotic', name='breed_type'), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', name='animal_sex'), nullable=False),
    sa.Column('lactation_number', sa.Integer(), nullable=True),
    sa.Column('body_condition_score', sa.Float(), nullable=True),
    sa.Column('is_insured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pashu_aadhaar_id')
    )
    op.create_table('community_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('disease_name', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), server_default='5.0', nullable=False),
    sa.Column('severity', sa.Enum('low', 'moderate', 'severe', 'critical', name='community_alert_severity'), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milk_collection_centers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('village_code', sa.String(length=20), nullable=True),
    sa.Column('manager_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sell_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.Enum('milk', 'eggs', 'goat_products', 'sheep_products', 'manure', 'wool', 'other', name='product_type'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=True),
    sa.Column('buyer_phone', sa.String(length=15), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shg_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('village_code', sa.String(length=20), nullable=True),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('member_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('women_only', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('formation_date', sa.Date(), nullable=True),
    sa.Column('total_savings', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('grading', sa.Enum('A', 'B', 'C', 'ungraded', name='shg_grading'), server_default='ungraded', nullable=False),
    sa.Column('panchsutra_compliance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('completed', 'pending', 'cancelled', name='transaction_status'), server_default='completed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('symptom', 'checkup', 'treatment', 'emergency', name='health_event_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_risk_score', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('probable_diseases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_policies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coverage_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'claimed', name='policy_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number')
    )
    op.create_table('medicine_administrations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('administered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawal_milk_until', sa.Date(), nullable=True),
    sa.Column('withdrawal_meat_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milk_collection_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('farmer_user_id', sa.UUID(), nullable=False),
    sa.Column('quantity_liters', sa.Float(), nullable=False),
    sa.Column('fat_pct', sa.Float(), nullable=True),
    sa.Column('snf_pct', sa.Float(), nullable=True),
    sa.Column('rate_per_liter', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('shift', sa.Enum('morning', 'evening', name='milk_session'), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['milk_collection_centers.id'], ),
    sa.ForeignKeyConstraint(['farmer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccinations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=200), nullable=False),
    sa.Column('administered_on', sa.Date(), nullable=False),
    sa.Column('next_due', sa.Date(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yield_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quantity_liters', sa.Float(), nullable=False),
    sa.Column('session', sa.Enum('morning', 'evening', name='milk_session'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_claims',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('filed', 'under_review', 'approved', 'rejected', name='claim_status'), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_claims')
    op.drop_table('yield_logs')
    op.drop_table('vaccinations')
    op.drop_table('milk_collection_records')
    op.drop_table('medicine_administrations')
    op.drop_table('insurance_policies')
    op.drop_table('health_events')
    op.drop_table('transactions')
    op.drop_table('shg_groups')
    op.drop_table('sell_records')
    op.drop_table('milk_collection_centers')
    op.drop_table('community_alerts')
    op.drop_table('animals')
    op.drop_table('weather_alerts')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('traditional_remedies')
    op.drop_table('medicines')
    op.drop_table('govt_schemes')
    op.drop_table('feed_ingredients')
    op.drop_table('advisory_tips')
    # ### end Alembic commands ###
