"""Karnataka APMC hardcoded market rates for livestock products."""

KARNATAKA_RATES = {
    "milk": {
        "unit": "liters",
        "min": 28.0,
        "max": 35.0,
        "avg": 31.5,
        "district": "Mysore",
        "label": "Cow Milk",
    },
    "eggs": {
        "unit": "pieces",
        "min": 5.0,
        "max": 7.0,
        "avg": 6.0,
        "district": "Mysore",
        "label": "Country Eggs",
    },
    "goat_milk": {
        "unit": "liters",
        "min": 60.0,
        "max": 80.0,
        "avg": 70.0,
        "district": "Mysore",
        "label": "Goat Milk",
    },
    "goat_meat": {
        "unit": "kg",
        "min": 600.0,
        "max": 800.0,
        "avg": 700.0,
        "district": "Mysore",
        "label": "Goat Meat (live weight)",
    },
    "sheep_meat": {
        "unit": "kg",
        "min": 500.0,
        "max": 700.0,
        "avg": 600.0,
        "district": "Mysore",
        "label": "Sheep Meat (live weight)",
    },
    "wool": {
        "unit": "kg",
        "min": 100.0,
        "max": 150.0,
        "avg": 125.0,
        "district": "Mysore",
        "label": "Raw Wool",
    },
    "manure": {
        "unit": "kg",
        "min": 2.0,
        "max": 5.0,
        "avg": 3.5,
        "district": "Mysore",
        "label": "Organic Manure / Vermicompost",
    },
    "buffalo_milk": {
        "unit": "liters",
        "min": 40.0,
        "max": 55.0,
        "avg": 47.5,
        "district": "Mysore",
        "label": "Buffalo Milk",
    },
    "ghee": {
        "unit": "kg",
        "min": 400.0,
        "max": 600.0,
        "avg": 500.0,
        "district": "Mysore",
        "label": "Desi Ghee",
    },
    "paneer": {
        "unit": "kg",
        "min": 280.0,
        "max": 350.0,
        "avg": 315.0,
        "district": "Mysore",
        "label": "Fresh Paneer",
    },
    "curd": {
        "unit": "kg",
        "min": 40.0,
        "max": 60.0,
        "avg": 50.0,
        "district": "Mysore",
        "label": "Fresh Curd",
    },
    "chicken_broiler": {
        "unit": "kg",
        "min": 150.0,
        "max": 200.0,
        "avg": 175.0,
        "district": "Mysore",
        "label": "Broiler Chicken (live)",
    },
    "chicken_country": {
        "unit": "kg",
        "min": 350.0,
        "max": 500.0,
        "avg": 425.0,
        "district": "Mysore",
        "label": "Country Chicken (live)",
    },
}
